package com.github.smartgwt_ext.server.generation;

import com.github.smartgwt_ext.server.introspection.BeanInformation;
import com.sun.codemodel.JAnnotationUse;
import com.sun.codemodel.JDefinedClass;

import javax.annotation.Generated;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author Andreas Berger (latest modification by $Author$)
 * @version $Id$
 * @created 05.09.14 - 15:43
 */
public class GenerationHelper {
	public static void addGeneratedInfo(
			JDefinedClass generatedClass,
			Class<?> generatorClass,
			BeanInformation<?> sourceClass,
			boolean addAnnotation) {
		generatedClass.javadoc().add("AUTO-GENERATED FILE - DO NOT EDIT\n\n"
				+ "<p>Generated by {@link " + generatorClass.getName() + "}</p>");
		if (sourceClass != null) {
			generatedClass.javadoc().add("\n<p>Generated from {@link " + sourceClass.getName() + "}</p>");
		}
		if (addAnnotation) {
			JAnnotationUse generated = generatedClass.annotate(Generated.class);
			generated.param("value", generatorClass.getName());
			generated.param("date", new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(new Date()));
		}
	}
}
